# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# On push commit id publish / dist folder upload
# on TAG pubish
# dist folder structure in typescript publish
# chat config interaces & chatwindow.ts

name: Kore-web-sdk

on:
  push:
    branches:
      - v2/dev 
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@uday_test'
      - name: Installing the dependencies   
        run: npm ci
      - name: Run the UMD build
        run: npm run build-umd
      - name: Run ESM build
        run: npm run build
      - name: Prepare and npm publish the build
        run: node npmPublish.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKENNPM }}


